#!/bin/bash
# Generated by organize_screens.py from 2idd_caqtdm_logs.txt
# Review caQtDM path, EPICS env, and macros before running.

# alias caQtDM="/APSshare/caqtdm/caqtdm-4.4.1/caQtDM_Binaries/rhel9-x86_64/caQtDM"

wmctrl -s 0
caQtDM -x -attach -dg +10+82 2ida_hutch.ui &
sleep 3
caQtDM -x -attach -dg +10+112 -macro "P=2idd:,M1=m1,M2=m2,M3=m3,M4=m4,M5=m5,M6=m6,M7=m7,M8=m8,M9=m9,M10=m10,M11=m11,M12=m12,M13=m13,M14=m14,M15=m15,M16=m16,M17=m17,M18=m18,M19=m19,M20=m20,M21=m21,M22=m22,M23=m23,M24=m24,M25=m25,M26=m26,M27=m27,M28=m28,M29=m29,M30=m30,M31=m31,M32=m32,M33=m33,M34=m34,M35=m35,M36=m36,M37=m37,M38=m38,M39=m39,M40=m40,M41=m41,M42=m42,M43=m43,M44=m44,M45=m45,M46=m46,M47=m47,M48=m48" topMotors.ui &
sleep 3
caQtDM -x -attach -dg +17+987 -macro "P=2ida2:,M1=m9,M2=m10,M3=m11,M4=m12,M5=m17,M6=m18,M7=m19,M8=m20" kohzuSeqCtl_All.ui &
sleep 3
caQtDM -x -attach -dg +151+483 -macro "P=2idd:,S=scaler1" scaler16_full.ui &
sleep 3
caQtDM -x -attach -dg +551+947 -macro "P=2iddfS1:,A=A1" SR570_tiny.ui &
sleep 3
caQtDM -x -attach -dg +555+1173 -macro "P=2iddfS1:,A=A2" SR570_tiny.ui &
sleep 3
caQtDM -x -attach -dg +620+491 -macro "P=2iddfS1:,S=s1:" XIA_shutter.ui &
sleep 3
caQtDM -x -attach -dg +742+948 -macro "P=2iddfS1:,A=A3" SR570_tiny.ui &
sleep 3
caQtDM -x -attach -dg +743+1171 -macro "P=2iddfS1:,A=A4" SR570_tiny.ui &
sleep 3
caQtDM -x -attach -dg +931+559 -macro "P=2idd:,S=scanAux,PO=2idd:,o_x=m11,o_y=m12,PS=2idd:,s=Slit_1,s_x=Slit1H,s_y=Slit1V,PC=2idd:,c_x=m1,c_y=m2,PZ=2idd:,z_x=m21,z_y=m4,z_z=m44,z_zl=m22,PT=2idd:,t_x=m40,t_y=m39,t_z=m36,p_x=m33,p_y=m35,mPV=2idd:,vx=junk,vy=m23,PE=2ida2:,PM=2idd:,PCS=2iddfS1:,DPCX=m19,DPCY=m7,B=1:" 2IDD_microscopeV2.ui &
sleep 3
caQtDM -x -attach -dg +1009+82 2idd_beamline.ui &
sleep 3
caQtDM -x -attach -dg +1500+578 -macro "P=2idd:,M1=m57,M2=m58,M3=m59,M4=m60,M5=m61,M6=m62,M7=m63,M8=m64" topMotors8.ui &
sleep 3
caQtDM -x -attach -dg +2009+82 -macro "He1=2idsft:userTran9.I,He2=2idsft:userTran9.J,He3=2idsft:userTran9.K,He4=2idsft:userTran9.L,Flo=2idsft:userTran9.O,Auto=2idsft:userTran3Enable,Ena=2idsft:userCalc3Enable,Opn=2idsft:userCalc3.VAL,Sns=2idsft:userTran9.M" He_levels.ui &
sleep 3

wmctrl -s 1
caQtDM -x -attach -dg +10+82 -macro "P=2idd:,N=H,S=scanH" scan_full.ui &
sleep 3
caQtDM -x -attach -dg +10+792 -macro "P=2idd:,N=1,S=scan1" scan_full.ui &
sleep 3
caQtDM -x -attach -dg +400+82 -macro "P=2idd:,N=2,S=scan2" scan_full.ui &
sleep 3
caQtDM -x -attach -dg +400+791 -macro "P=2idd:F,N=1,S=scan1" scan_full.ui &
sleep 3
caQtDM -x -attach -dg +793+82 -macro "P=2idd:F,N=H,S=scanH" scan_full.ui &
sleep 3
caQtDM -x -attach -dg +794+790 -macro "P=2idd:" scan_saveData.ui &
sleep 3
caQtDM -x -attach -dg +795+1088 -macro "P=2iddXMAP:,M=mca1" simple_mca.ui &
sleep 3
caQtDM -x -attach -dg +1179+659 -macro "P=2iddXMAP:, R=netCDF1:" NDFileNetCDF.ui &
sleep 3
caQtDM -x -attach -dg +1184+82 -macro "P=2iddXMAP:" mappingControl.ui &
sleep 3
caQtDM -x -attach -dg +1311+82 -macro "P=2iddXMAP:,D=dxp,M=mca" 4element_dxp.ui &
sleep 3
caQtDM -x -attach -dg +1374+846 -macro "P=2idd:,B=1" batchscan_v5.ui &
sleep 3
caQtDM -x -attach -dg +1890+82 -macro "P=2idd:3820:" SIS38XX.ui &
sleep 3

wmctrl -s 2
caQtDM -x -attach -dg +1500+82 -macro "P=2idAV6:,R=HDF1:,EXT=h5" NDFileHDF5.ui &
sleep 3
caQtDM -x -attach -dg +1508+579 -macro "P=2idAV6:, R=cam1:, C=FLIR_ORX_10G_51S5M" ADAravis.ui &
sleep 3

wmctrl -s 3
caQtDM -x -attach -dg +1500+519 -macro "P=2idAV6:, R=cam1:, C=FLIR_ORX_10G_51S5M" ADAravis.ui &
sleep 3
