#!/bin/bash
# Generated by organize_screens.py from 2xfm_screens.txt
# Review caQtDM path, EPICS env, and macros before running.

# alias caQtDM="/APSshare/caqtdm/caqtdm-4.4.1/caQtDM_Binaries/rhel9-x86_64/caQtDM"

wmctrl -s 0
caQtDM -x -attach -dg +10+483 2xfm_beamline.ui &
sleep 3
caQtDM -x -attach -dg +11+82 2ida_hutch.ui &
sleep 3
caQtDM -x -attach -dg +472+957 kohzuSeqCtl_All.ui &
sleep 3
caQtDM -x -attach -dg +1011+82 topMotors.ui &
sleep 3
caQtDM -x -attach -dg +1160+309 topMotors8.ui &
sleep 3
caQtDM -x -attach -dg +1161+83 topMotors8.ui &
sleep 3
caQtDM -x -attach -dg +1161+535 topMotors8.ui &
sleep 3
caQtDM -x -attach -dg +1307+336 XIA_shutter.ui &
sleep 3
caQtDM -x -attach -dg +1310+93 motorx_more.ui &
sleep 3

wmctrl -s 2
caQtDM -x -attach -dg +10+84 IDControl_Planar.adl &
sleep 3
caQtDM -x -attach -dg +12+749 motorx_more.ui &
sleep 3
caQtDM -x -attach -dg +321+84 2ide_microscope.ui &
sleep 3
caQtDM -x -attach -dg +383+748 motorx_more.ui &
sleep 3
caQtDM -x -attach -dg +754+750 motorx_more.ui &
sleep 3
caQtDM -x -attach -dg +1126+750 motorx_more.ui &
sleep 3
caQtDM -x -attach -dg +1498+750 motorx_more.ui &
sleep 3
caQtDM -x -attach -dg +1874+752 motorx_more.ui &
sleep 3

wmctrl -s 3
caQtDM -x -attach -dg +10+83 simple_mca_small.ui &
sleep 3
caQtDM -x -attach -dg +10+349 simple_mca_small.ui &
sleep 3
caQtDM -x -attach -dg +13+617 scan_full.ui &
sleep 3
caQtDM -x -attach -dg +402+617 scan_full.ui &
sleep 3
caQtDM -x -attach -dg +463+351 simple_mca_small.ui &
sleep 3
caQtDM -x -attach -dg +466+85 simple_mca_small.ui &
sleep 3
caQtDM -x -attach -dg +793+620 mappingControl.ui &
sleep 3
caQtDM -x -attach -dg +920+84 NDFileNetCDF.ui &
sleep 3
caQtDM -x -attach -dg +1617+87 4element_dxp.ui &
sleep 3
caQtDM -x -attach -dg +2199+85 SIS38XX.ui &
sleep 3
caQtDM -x -attach -dg +2637+84 2ide_scan_setup.ui &
sleep 3
